# Gitleaks configuration for Puppeteer MCP
# @nist au-3 "Content of audit records"
# @nist si-4 "System monitoring"

title = "Puppeteer MCP Gitleaks Configuration"

[allowlist]
description = "Allowlist for Puppeteer MCP"

# Paths to completely ignore
paths = [
    '''node_modules''',
    '''dist''',
    '''coverage''',
    '''\.git''',
    '''package-lock\.json''',
    '''test-results''',
    '''\.next''',
    '''\.cache''',
    '''build''',
    '''site''',  # Generated documentation site
    '''eslint-results\.json''',  # ESLint results
    '''\.env\.example''',  # Example environment file
    '''\.env\.sample''',  # Sample environment file
    '''\.env\.template''',  # Template environment file
    '''work/''',  # Temporary work directory
    '''\.sarif$''',  # SARIF result files
]

# Specific file commits to allow
commits = [
    "869a91bbcff8ed698163b57818e1b69080aacd4b",  # mkdocs.yml documentation update
    "494064dd60bd59131ee339262f6f734cd1bddbc7",  # Test files with mock data
    "48c14afef50daefb57d25b510146871e9fca22e7",  # TypeScript definitions
]

# Allow test/demo credentials that are clearly marked
regexes = [
    '''demo[_-]?(?:password|token|key|secret)''',
    '''test[_-]?(?:password|token|key|secret|token)''',
    '''example[_-]?(?:password|token|key|secret)''',
    '''fake[_-]?(?:password|token|key|secret)''',
    '''dummy[_-]?(?:password|token|key|secret)''',
    '''mcp-demo-salt''',  # Our demo salt in user-service.ts
    # JWT examples in documentation (always truncated with ...)
    '''eyJ[A-Za-z0-9\-_]+\.\.\.''',
    # Test secret keys
    '''test-secret-key-for-testing-only.*''',
    # Example API keys in documentation
    '''sk-(test|example|readonly|your).*''',
    '''sk-[0-9]+abcdef''',
    # Mock/example tokens in JSON
    '''"token":\s*"[A-Za-z0-9\-_]+\.\.\."''',
    '''"credentials":\s*"[A-Za-z0-9\-_]+\.\.\."''',
    '''"accessToken":\s*"[A-Za-z0-9\-_]+\.\.\."''',
    # Bearer tokens in examples
    '''Bearer\s+eyJ[A-Za-z0-9\-_]+\.\.\.''',
    '''authorization.*Bearer\s+eyJ[A-Za-z0-9\-_]+\.\.\.''',
    # Placeholder values from .env.example
    '''your-super-secret.*''',
    '''postgresql://user:password@localhost''',
    '''redis://localhost:6379''',
    '''http://localhost:[0-9]+''',
    '''https://example\.com''',
    # Common placeholder patterns
    '''<[A-Z_]+>''',  # <API_KEY>, <SECRET>, etc.
    '''xxx+''',  # xxxxx placeholders
    '''\$\{[A-Z_]+\}''',  # ${API_KEY} style placeholders
    # Specific patterns from our codebase
    '''credentials:\s*['"]test-token['"]''',
    '''apikey['"]?:\s*['"]test-api-key['"]''',
    '''token['"]?:\s*['"]test-jwt-token['"]''',
    '''pymdownx\.\w+''',  # MkDocs extensions in mkdocs.yml
    # TypeScript type definitions
    '''interface\s+\w+\s*\{[^}]*(?:token|key|secret)[^}]*\}''',
    '''type\s+\w+\s*=\s*\{[^}]*(?:token|key|secret)[^}]*\}''',
]

# Custom entropy settings
[extend]
# Lower entropy threshold for better detection
entropy_threshold = 3.0