# Gitleaks configuration for Puppeteer MCP
# @nist au-3 "Content of audit records"
# @nist si-4 "System monitoring"

title = "Puppeteer MCP Gitleaks Configuration"

[allowlist]
description = "Allowlist for Puppeteer MCP"
paths = [
    '''node_modules''',
    '''dist''',
    '''coverage''',
    '''\.git''',
    '''package-lock\.json''',
    '''test-results''',
    '''\.next''',
    '''\.cache''',
    '''build''',
    '''site''',  # Generated documentation site
    '''\.github/workflows''',  # Workflow files may have example tokens
    '''eslint-results\.json''',  # ESLint results
    '''tests?/.*\.test\.(ts|js)$''',  # Test files
    '''.*\.md$''',  # Markdown documentation files
    '''src/mcp/examples''',  # Example files with demo credentials
    '''\.env\.example''',  # Example environment file
    '''\.env\.sample''',  # Sample environment file
    '''\.env\.template''',  # Template environment file
]

# Allow test/demo credentials that are clearly marked
regexes = [
    '''demo[_-]?(?:password|token|key|secret)''',
    '''test[_-]?(?:password|token|key|secret)''',
    '''example[_-]?(?:password|token|key|secret)''',
    '''fake[_-]?(?:password|token|key|secret)''',
    '''dummy[_-]?(?:password|token|key|secret)''',
    '''mcp-demo-salt''',  # Our demo salt in user-service.ts
    # JWT examples in documentation (always truncated with ...)
    '''eyJ[A-Za-z0-9\-_]+\.\.\.''',
    # Test secret keys
    '''test-secret-key-for-testing-only.*''',
    # Example API keys in documentation
    '''sk-(test|example|readonly|your).*''',
    '''sk-[0-9]+abcdef''',
    # Mock/example tokens in JSON
    '''"token":\s*"[A-Za-z0-9\-_]+\.\.\."''',
    '''"credentials":\s*"[A-Za-z0-9\-_]+\.\.\."''',
    '''"accessToken":\s*"[A-Za-z0-9\-_]+\.\.\."''',
    # Bearer tokens in examples
    '''Bearer\s+eyJ[A-Za-z0-9\-_]+\.\.\.''',
    '''authorization.*Bearer\s+eyJ[A-Za-z0-9\-_]+\.\.\.''',
    # Placeholder values from .env.example
    '''your-super-secret.*''',
    '''postgresql://user:password@localhost''',
    '''redis://localhost:6379''',
    '''http://localhost:[0-9]+''',
    '''https://example\.com''',
    # Common placeholder patterns
    '''<[A-Z_]+>''',  # <API_KEY>, <SECRET>, etc.
    '''xxx+''',  # xxxxx placeholders
    '''\$\{[A-Z_]+\}''',  # ${API_KEY} style placeholders
]

# Additional rules for common false positives
[[rules]]
id = "ignore-package-json-author"
description = "Ignore package.json author fields"
path = '''package\.json'''
regex = '''(?i)(author|email)'''

[[rules]]
id = "ignore-typescript-definitions"
description = "Ignore TypeScript type definitions"
path = '''\.d\.ts$'''
regex = '''.*'''

[[rules]]
id = "ignore-test-mock-secrets"
description = "Ignore test files with mock data"
path = '''(test|spec|__tests__|__mocks__)'''
regex = '''(?i)(secret|password|token|key|credential)'''

[[rules]]
id = "ignore-documented-examples"
description = "Ignore documented examples"
path = '''(README|CONTRIBUTING|docs)'''
regex = '''(?i)(secret|password|token|key|credential)'''

[[rules]]
id = "ignore-jwt-in-tests"
description = "Ignore JWT tokens in test files"
path = '''.*\.test\.(ts|js)$'''
regex = '''eyJ[A-Za-z0-9\-_]+'''

[[rules]]
id = "ignore-example-jwt-tokens"
description = "Ignore example JWT tokens"
path = '''(examples?|docs?|README)'''
regex = '''eyJ[A-Za-z0-9\-_]+'''

[[rules]]
id = "ignore-test-api-keys"
description = "Ignore test API keys"
path = '''.*\.(test|spec)\.(ts|js)$'''
regex = '''sk-[a-zA-Z0-9]+'''

# Custom entropy settings
[extend]
# Lower entropy threshold for better detection
entropy_threshold = 3.0