# Docker Compose Override for Local Development
# This file is automatically loaded by docker-compose
# It overrides settings in docker-compose.yml for local development

version: '3.8'

services:
  app:
    build:
      target: development
      dockerfile: Dockerfile.dev
    environment:
      # Override for local development
      - LOG_LEVEL=debug
      - LOG_FORMAT=pretty
      - NODE_ENV=development
      - DEBUG=puppeteer-mcp:*
      
      # Disable security features for easier development
      - TLS_ENABLED=false
      - CORS_ORIGIN=*
      - RATE_LIMIT_MAX_REQUESTS=1000
      
      # Local development secrets (DO NOT USE IN PRODUCTION)
      - JWT_SECRET=local-dev-jwt-secret-32-characters-minimum
      - SESSION_SECRET=local-dev-session-secret-32-chars-min
      
      # Development telemetry
      - TELEMETRY_TRACE_SAMPLING_RATE=1.0
      - TELEMETRY_DEBUG=true
      - TELEMETRY_LOG_LEVEL=debug
      
      # Browser pool settings for development
      - BROWSER_POOL_MAX_SIZE=2
      - PUPPETEER_HEADLESS=false  # Show browser for debugging
      
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:delegated
      - ./tests:/app/tests:delegated
      - ./scripts:/app/scripts:delegated
      
      # Mount config files
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./jest.config.mjs:/app/jest.config.mjs:ro
      - ./nodemon.json:/app/nodemon.json:ro
      - ./.env:/app/.env:ro
      
      # Persist npm cache between rebuilds
      - npm-cache:/home/nodejs/.npm
      
    stdin_open: true
    tty: true
    
  redis:
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --requirepass redis-dev-password
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --loglevel debug
      --save 60 1
      --save 300 10
      --save 900 100
    
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mcp-password
      - POSTGRES_LOG_STATEMENT=all
      - POSTGRES_LOG_CONNECTIONS=on
      - POSTGRES_LOG_DISCONNECTIONS=on
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c log_statement=all
      -c log_duration=on
      
  # Always include development tools in override
  adminer:
    profiles: []  # Remove profile restriction
    
  redis-commander:
    profiles: []  # Remove profile restriction

volumes:
  npm-cache:
    driver: local