# MkDocs Configuration for Puppeteer MCP
# Following Knowledge Management Standards v1.0.0

site_name: Puppeteer MCP Documentation
site_description: AI-Enabled Browser Automation Platform with Multi-Protocol Support
site_author: William Zujkowski
site_url: https://williamzujkowski.github.io/puppeteer-mcp/
repo_url: https://github.com/williamzujkowski/puppeteer-mcp
repo_name: puppeteer-mcp
edit_uri: edit/main/docs/
strict: false # Temporarily disabled for initial setup

# Theme Configuration
theme:
  name: material
  language: en

  # Color scheme
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Features
  features:
    - announce.dismiss # Dismissable announcements
    - content.action.edit # Edit page button
    - content.action.view # View source button
    - content.code.annotate # Code annotations
    - content.code.copy # Code copy button
    - content.code.select # Code selection button
    - content.tabs.link # Link content tabs
    - content.tooltips # Improved tooltips
    - navigation.expand # Expand all sections by default
    - navigation.footer # Previous/next footer
    - navigation.indexes # Section index pages
    - navigation.instant # Instant loading
    - navigation.instant.prefetch # Prefetch resources
    - navigation.instant.progress # Loading progress bar
    - navigation.path # Breadcrumbs
    - navigation.prune # Prune navigation tree
    - navigation.sections # Render sections as groups
    - navigation.tabs # Top-level navigation tabs
    - navigation.tabs.sticky # Sticky navigation tabs
    - navigation.top # Back to top button
    - navigation.tracking # Anchor tracking
    - search.highlight # Search term highlighting
    - search.share # Share search results
    - search.suggest # Search suggestions
    - toc.follow # Table of contents follows scroll
    - toc.integrate # Integrate ToC into navigation

  # Icons
  icon:
    repo: fontawesome/brands/github
    logo: material/robot

  # Fonts
  font:
    text: Roboto
    code: Roboto Mono

# Navigation Structure
nav:
  - Home:
      - Welcome: index.md
      - Quick Start: quickstart/index.md
      - Architecture Overview: architecture/overview.md

  - Getting Started:
      - Installation: quickstart/installation.md
      - First Steps: quickstart/first-steps.md
      - Claude Desktop Setup: quickstart/claude-desktop.md
      - Configuration: quickstart/configuration.md
      - Troubleshooting: troubleshooting.md

  - Quick Reference:
      - API Cheat Sheet: quick-reference/api-cheatsheet.md
      - Common Patterns: quick-reference/common-patterns.md
      - Environment Variables: quick-reference/env-vars.md
      - Error Codes: quick-reference/error-codes.md
      - MCP Tools Summary: quick-reference/mcp-tools-summary.md

  - User Guides:
      - guides/index.md
      - Browser Automation: guides/browser-automation.md
      - API Integration: guides/api-integration.md
      - MCP Usage Examples: guides/mcp-usage-examples.md
      - Advanced Scenarios: guides/advanced-scenarios.md

  - API Reference:
      - reference/index.md
      - REST API: reference/rest-api.md
      - gRPC API: reference/grpc-api.md
      - WebSocket API: reference/websocket-api.md
      - MCP Tools: reference/mcp-tools.md
      - Puppeteer Actions: reference/puppeteer-actions.md

  - Deployment:
      - deployment/index.md
      - NPM Package: deployment/npm-package.md
      - Docker: deployment/docker.md
      - Production Setup: deployment/production.md
      - Scaling Guide: deployment/scaling.md

  - Architecture:
      - architecture/index.md
      - System Design: architecture/overview.md
      - Session Management: architecture/session-management.md
      - Security Model: architecture/security.md
      - MCP Integration: architecture/mcp-integration-plan.md

  - Development:
      - development/index.md
      - Development Workflow: development/workflow.md
      - Coding Standards: development/standards.md
      - Testing Guide: development/testing.md
      - AI Patterns: ai/routing-patterns.md

  - Contributing:
      - contributing/index.md
      - Code of Conduct: contributing/code-of-conduct.md
      - How to Contribute: contributing.md
      # Security Policy is in root SECURITY.md

  - Resources:
      # Changelog is in root CHANGELOG.md
      - Roadmap: project/roadmap.md
      - Lessons Learned: lessons/implementation.md
      - Planning Insights: lessons/project-planning.md

# Plugins
plugins:
  - search:
      separator: '[\s\-\.]'
      lang:
        - en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
      fallback_to_build_date: true
      timezone: UTC
  - tags
  - redirects:
      redirect_maps:
        'getting-started.md': 'quickstart/index.md'
        'quickstart-npm.md': 'quickstart/installation.md'
        'npm-package.md': 'deployment/npm-package.md'
        'deployment/npm-global.md': 'deployment/npm-package.md'
        'guides/getting-started.md': 'quickstart/index.md'
        'guides/deployment.md': 'deployment/index.md'
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print Version'
      add_print_site_banner: true
      print_site_banner_template: 'docs/assets/pdf/banner.tpl'
      path_to_pdf: 'assets/pdf/puppeteer-mcp-docs.pdf'
      include_css: true
      enabled: true

# Markdown Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS
extra_css:
  - stylesheets/extra.css
  - stylesheets/quickref.css

# Extra JavaScript
extra_javascript: []
  # - javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - javascripts/tablesort.js

# Analytics (if needed)
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX

# Extra Configuration
extra:
  # Announcement bar
  homepage: https://github.com/williamzujkowski/puppeteer-mcp

  # Social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/williamzujkowski/puppeteer-mcp
      name: GitHub Repository
    - icon: fontawesome/brands/npm
      link: https://www.npmjs.com/package/puppeteer-mcp
      name: NPM Package
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/williamzujkowski
      name: LinkedIn Profile
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/williamzujkowski/puppeteer-mcp
      name: Docker Hub

  # Version selector
  version:
    provider: mike
    default: latest

  # Tags
  tags:
    Browser Automation: browser
    API: api
    MCP: mcp
    Security: security
    Docker: docker
    TypeScript: typescript
    Testing: testing

  # Analytics
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: Thanks for your feedback!

  # Cookie consent
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage

# Copyright
copyright: |
  Copyright &copy; 2025 William Zujkowski - Apache License 2.0<br>
  <a href="#__consent">Cookie Settings</a> |
  <a href="/privacy/">Privacy Policy</a> |
  <a href="/terms/">Terms of Service</a>
